config/routes.rb
Enki::Application.routes.draw do


resources :supports, :only => [:new, :create]


  match '/contact', :to => 'supports#new'
  match '/about',   :to => 'pages#about'
  match '/map',   :to => 'pages#map'
  match '/pictures',   :to => 'pages#index'

  namespace 'admin' do
    resource :session

    resources :posts, :pages do
      post 'preview', :on => :collection
    end
    resources :comments
    resources :undo_items do
      post 'undo', :on => :member
    end

    match 'health(/:action)' => 'health', :action => 'index', :as => :health

    root :to => 'dashboard#show'
  end

  resources :archives, :only => [:index]
  resources :pages, :only => [:show]

  constraints :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ do
    post ':year/:month/:day/:slug/comments' => 'comments#index'
    get ':year/:month/:day/:slug/comments/new' => 'comments#new'
    get ':year/:month/:day/:slug' => 'posts#show'
  end

  scope :to => 'posts#index' do
    get 'posts.:format', :as => :formatted_posts
    get '(:tag)', :as => :posts
  end

  root :to => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  DEFAULT_LIMIT = 15

  acts_as_taggable

  has_many                :comments, :dependent => :destroy
  has_many                :approved_comments, :class_name => 'Comment'

  before_validation       :generate_slug
  before_validation       :set_dates
  before_save             :apply_filter

  validates_presence_of   :title, :slug, :body

  validate                :validate_published_at_natural

  def validate_published_at_natural
    errors.add("published_at_natural", "Unable to parse time") unless published?
  end

  attr_accessor :minor_edit
  def minor_edit
    @minor_edit ||= "1"
  end

  def minor_edit?
    self.minor_edit == "1"
  end
  
  def get_image
    return image || "default.jpg"
  end

  def published?
    published_at?
  end

  attr_accessor :published_at_natural
  def published_at_natural
    @published_at_natural ||= published_at.send_with_default(:strftime, 'now', "%Y-%m-%d %H:%M")
  end

  class << self
    def build_for_preview(params)
      post = Post.new(params)
      post.generate_slug
      post.set_dates
      post.apply_filter
      TagList.from(params[:tag_list]).each do |tag|
        post.tags << Tag.new(:name => tag)
      end
      post
    end

    def find_recent(options = {})
      tag = options.delete(:tag)
      options = {
        :order      => 'posts.published_at DESC',
        :conditions => ['published_at < ?', Time.zone.now],
        :limit      => DEFAULT_LIMIT
      }.merge(options)
      if tag
        find_tagged_with(tag, options)
      else
        find(:all, options)
      end
    end

    def find_by_permalink(year, month, day, slug, options = {})
      begin
        day = Time.parse([year, month, day].collect(&:to_i).join("-")).midnight
        post = find_all_by_slug(slug, options).detect do |post|
          [:year, :month, :day].all? {|time|
            post.published_at.send(time) == day.send(time)
          }
        end
      rescue ArgumentError # Invalid time
        post = nil
      end
      post || raise(ActiveRecord::RecordNotFound)
    end

    def find_all_grouped_by_month
      posts = find(
        :all,
        :order      => 'posts.published_at DESC',
        :conditions => ['published_at < ?', Time.now]
      )
      month = Struct.new(:date, :posts)
      posts.group_by(&:month).inject([]) {|a, v| a << month.new(v[0], v[1])}
    end
  end

  def destroy_with_undo
    transaction do
      self.destroy
      return DeletePostUndo.create_undo(self)
    end
  end

  def month
    published_at.beginning_of_month
  end

  def apply_filter
    self.body_html = EnkiFormatter.format_as_xhtml(self.body)
  end

  def set_dates
    self.edited_at = Time.now if self.edited_at.nil? || !minor_edit?
    self.published_at = Chronic.parse(self.published_at_natural)
  end

  def denormalize_comments_count!
    Post.update_all(["approved_comments_count = ?", self.approved_comments.count], ["id = ?", self.id])
  end

  def generate_slug
    self.slug = self.title.dup if self.slug.blank?
    self.slug.slugorize!
  end

  # TODO: Contribute this back to acts_as_taggable_on_steroids plugin
  def tag_list=(value)
    value = value.join(", ") if value.respond_to?(:join)
    super(value)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_filter :find_post, :only => [:show, :update, :destroy]

  def index
    respond_to do |format|
      format.html {
        @posts = Post.paginate(
          :order => "published_at DESC",
          :page  => params[:page]
        )
      }
    end
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      respond_to do |format|
        format.html {
          flash[:notice] = "Created post '#{@post.title}'"
          redirect_to(:action => 'show', :id => @post)
        }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new',         :status => :unprocessable_entity }
      end
    end
  end

  def update
    if @post.update_attributes(params[:post])
      respond_to do |format|
        format.html {
          flash[:notice] = "Updated post '#{@post.title}'"
          redirect_to(:action => 'show', :id => @post)
        }
      end
    else
      respond_to do |format|
        format.html { render :action => 'show',        :status => :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html {
        render :partial => 'post', :locals => {:post => @post} if request.xhr?
      }
    end
  end

  def new
    @post = Post.new
  end

  def preview
    @post = Post.build_for_preview(params[:post])

    respond_to do |format|
      format.js {
        render :partial => 'posts/post.html.erb', :locals => {:post => @post}
      }
    end
  end

  def destroy
    undo_item = @post.destroy_with_undo

    respond_to do |format|
      format.html do
        flash[:notice] = "Deleted post '#{@post.title}'"
        redirect_to :action => 'index'
      end
      format.json {
        render :json => {
          :undo_path    => undo_admin_undo_item_path(undo_item),
          :undo_message => undo_item.description,
          :post         => @post.attributes
        }
      }
    end
  end
  

  protected


  def find_post
    @post = Post.find(params[:id])
  end



  
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @tag = params[:tag]
    @posts = Post.find_recent(:tag => @tag, :include => :tags).paginate(:page => params[:page], :order => 'published_at DESC', :per_page=>5)

    respond_to do |format|
      format.html
      format.atom { render :layout => false }
    end
  end

  def show
    @post = Post.find_by_permalink(*([:year, :month, :day, :slug].collect {|x| params[x] } << {:include => [:approved_comments, :tags]}))
    @comment = Comment.new
  end
  
def feed
    @posts = Post.all(:select => "title, author, id, content, posted_at", :order => "posted_at DESC", :limit => 20) 

    respond_to do |format|
      format.html
      format.rss { render :layout => false } #index.rss.builder
    end
end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  # This isn't strictly correct, but it's a pretty good guess
  # and saves another hit to the DB
  def more_content?
    @posts.size == Post::DEFAULT_LIMIT
  end
  
  def summarize(body, length)
    return simple_format(truncate(body.gsub(/<\/?.*?>/,  ""), :length => length)).gsub(/<\/?.*?>/,  "")
  end

  
end

app/views/posts/_extractpicture.html.erb
<%= link_to(image_tag("https://s3.amazonaws.com/alifeofplentyimages/photos/" + post.get_image), post_path(post)) %>

app/views/posts/_post.html.erb
 <h2><%= link_to(post.title, post_path(post)) %></h2>
<div class="entrybody">
 
  <%=raw post.body_html %>
</div>
<div class="meta">
  <ul>
    <li class="date">Posted on <%= format_post_date(post.published_at) %></li>
    <li class="comments"><%= link_to(pluralize(post.approved_comments.size, "comment"), post_path(post, :anchor => 'comments')) %></li>
    <% unless post.tags.empty? -%>
    <li class="tags">Tagged <%= linked_tag_list(post.tags) %></li>
    <% end -%>
  </ul>
</div>

app/views/posts/_postindex.html.erb
 <h2><%= link_to(post.title, post_path(post)) %></h2>


 <% if post.id.even? -%> 
<table>

      <tr>
      <td><%= render :partial => 'extractpicture', :locals => {:post => post} %></td>
      <td><%= render :partial => 'postsummarize', :locals => {:post => post} %></td>
      </tr>
</table>

<% else -%>

<table>

      <tr>
      <td><%= render :partial => 'postsummarize', :locals => {:post => post} %></td>
      <td><%= render :partial => 'extractpicture', :locals => {:post => post} %></td>
      </tr>
</table>
 

<% end %>

app/views/posts/_postsummarize.html.erb
<div class="entrybody">

  <%= summarize(raw(post.body_html), 500) %> <%= link_to("More", post_path(post)) %>
  </div>

<div class="meta">
  <ul>
    <li class="date">Posted on <%= format_post_date(post.published_at) %></li>
    <li class="comments"><%= link_to(pluralize(post.approved_comments.size, "comment"), post_path(post, :anchor => 'comments')) %></li>
    <% unless post.tags.empty? -%>
    <li class="tags">Tagged <%= linked_tag_list(post.tags) %></li>
    <% end -%>
  </ul>

app/views/posts/index.html.erb
<% content_for(:page_title) do %><%= posts_title(@tag) %><% end -%>
<% content_for(:head)       do %><%= auto_discovery_link_tag(:atom, @tag.nil? ? formatted_posts_path(:format => 'atom') : posts_path(:tag => @tag, :format => 'atom')) %><% end -%>

<% if @posts.empty? -%>
	<p>There are no posts yet.</p>
<% else -%>
	<% @posts.each do |post| -%>
	<div class="post post-<%= post.id %>">
	  <%= render :partial => 'postindex', :locals => {:post => post} %>
	</div>
	<% end -%>
  <% if more_content? -%>
    <div class="related">Looking for more? Head on over to the <%= link_to("archives", archives_path) %>.</div>
  <% end -%>
<% end -%>

<div style="text-align:center"> <%= will_paginate %> </div>

app/views/posts/show.html.erb
<% content_for(:head) do -%>
  <%= javascript_include_tag 'common' %>
  <%= javascript_include_tag 'live-comment-preview' %>
<% end -%>
<% content_for(:page_title) do -%>
<%= post_title(@post) -%>
<% end -%>
<%= render :partial => 'posts/post', :locals => {:post => @post} %>
<br>
<ul class="commentlist">
  <% @post.approved_comments.each do |comment| -%>
  <li<%=raw cycle(' class="alt"', '') %> id="comment-<%= comment.id %>">
    <%= render :partial => 'comments/comment', :locals => {:comment => comment} %>
  </li>
  <% end -%>
</ul>
<div class="related">Looking for more? Head on over to the <%= link_to("archives", archives_path) %>.</div>
<h2>Post a comment</h2>
  <% unless @comment.errors.empty? -%>
  <div class="errors">
    <h3>Comment not added!</h3>
    <ul>
      <% @comment.errors.sort_by(&:first).each do |error| -%>
        <li><%= format_comment_error(error) %></li>
      <% end -%>
    </ul>
  </div>
  <% end -%>
<%= form_for([@post, @comment]) do |form| -%>
  <div>
    <p><%= form.text_field 'author' %><label for="comment_author"><small>Name or <a href="http://openidexplained.com/">OpenID</a> (required)</small></label></p>
    <p><%= form.text_area 'body' %><br><small>(<a href="http://lesstile.rubyforge.org">lesstile enabled</a> - surround code blocks with ---)</small></p>
    <p><%= submit_tag "Add Comment" %></p>
  </div>
<% end -%>