config/routes.rb
Enki::Application.routes.draw do


resources :supports, :only => [:new, :create]


  match '/contact', :to => 'supports#new'
  match '/about',   :to => 'pages#about'
  match '/map',   :to => 'pages#map'
  match '/pictures',   :to => 'pages#index'

  namespace 'admin' do
    resource :session

    resources :posts, :pages do
      post 'preview', :on => :collection
    end
    resources :comments
    resources :undo_items do
      post 'undo', :on => :member
    end

    match 'health(/:action)' => 'health', :action => 'index', :as => :health

    root :to => 'dashboard#show'
  end

  resources :archives, :only => [:index]
  resources :pages, :only => [:show]

  constraints :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ do
    post ':year/:month/:day/:slug/comments' => 'comments#index'
    get ':year/:month/:day/:slug/comments/new' => 'comments#new'
    get ':year/:month/:day/:slug' => 'posts#show'
  end

  scope :to => 'posts#index' do
    get 'posts.:format', :as => :formatted_posts
    get '(:tag)', :as => :posts
  end

  root :to => 'posts#index'
end

app/views/layouts/_ga.html.erb
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-24198726-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8">

  <title><%= enki_config[:title] %> - Admin</title>

  <%= csrf_meta_tag %>

  <%= javascript_include_tag 'jquery.js' %>
  <%= javascript_include_tag 'jquery.livequery.js' %>
  <%= javascript_include_tag 'jquery.form.js' %>
  <%= javascript_include_tag 'jquery.easing.1.3.js' %>
  <%= javascript_include_tag 'rails.js' %>
  <%= javascript_include_tag 'humanmsg' %>
  <%= javascript_include_tag 'admin/shortcut' %>
  <%= javascript_include_tag 'admin/common' %>
  <%= stylesheet_link_tag 'formtastic' %>
  <%= stylesheet_link_tag 'humanmsg' %>
  <%= stylesheet_link_tag 'admin' %>
  <%= yield(:head) %>

  <% if flash[:notice] -%>
  <script>
    jQuery(document).ready(function() {
      humanMsg.displayMsg('<%= escape_javascript(flash[:notice]) %>');
    })
  </script>
  <% end -%>

</head>
<body>
  <div id="page">
    <div id="content">
      <%= yield %>
    </div>
    <div id="nav">
      <ul>
        <li><%= nav_link_to("Dashboard", admin_root_path,       :accesskey => '1') %></li>
        <li><%= nav_link_to("Posts",     admin_posts_path,      :accesskey => '2') %> <%= nav_link_to("(+)", new_admin_post_path, :accesskey => 'n') %></li>
        <li><%= nav_link_to("Pages",     admin_pages_path,      :accesskey => '3') %> <%= nav_link_to("(+)", new_admin_page_path, :accesskey => 'p') %></li>
        <li><%= nav_link_to("Comments",  admin_comments_path,   :accesskey => '4') %></li>
        <li><%= nav_link_to("Actions",   admin_undo_items_path, :accesskey => '5') %></li>
        <li><%= nav_link_to("Health",    admin_health_path,     :accesskey => '6') %></li>
        <li class="separator">&nbsp;</li>
        <li><%= link_to("Logout", admin_session_path, :accesskey => 'l', :method => :delete) %></li>
        <li><%= link_to("View Site", '/',             :accesskey => 'v', :title => 'View Site') %></li>
      </ul>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8">
  <title>A Life of Plenty</title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'rails' %>
  <%= javascript_include_tag 'aqtree3clickable' %>
  <script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

   <%= open_id_delegation_link_tags(enki_config[:open_id_delegation, :server], enki_config[:open_id_delegation, :delegate]) if enki_config[:open_id_delegation] %>
  <%= yield(:head) %>
</head>

      <div id= "header">
      <h1> A Life of Plenty </h1>
                <div id="navigation">
        <ul>
          <% page_links_for_navigation.each do |link| -%>
            <li><%= link_to(link.name, link.url) %></li>
          <% end -%>
        </ul>
          </div>
      </div>
<body>
  <div id="page_container">

        <% unless category_links_for_navigation.empty? -%>
        <div id= "menu">

          <h2>Tags</h2>
          <ul>
            <% category_links_for_navigation.each do |link| -%>
              <li><%= link_to(link.name, link.url) %></li>
            <% end -%>
          </ul>

          <% end -%>
      </div>
    <div id="content">
      <h1 id="page_heading"></h1>

      <div id="main">
        <%= yield %>
      </div>



      <div id="footer"> <%= auto_discovery_link_tag(:rss, "http://alifeofplenty.heroku.com") %></div>
    </div>
  </div>
<%= render :partial => 'layouts/ga' if RAILS_ENV == 'production' %>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8">

  <title><%= enki_config[:title] %> - Admin Login</title>

  <%= stylesheet_link_tag 'login' %>
</head>
<body>
  <div id="page">
    <div id="content">
      <%= yield %>
    </div>
    <div id="nav">
      <ul>
        <li><%= link_to("View Site", '/', :title => 'View Site') %></li>
      </ul>
    </div>
  </div>
</body>
</html>